#!/usr/bin/python3
import pytesseract
import sys
import argparse
try:
    import Image
except ImportError:
    from PIL import Image
from subprocess import check_output

def resolve(path):
    print("Resampling the image")
    check_output(['convert', path, '-resample', '600', path])
    return pytesseract.image_to_string(Image.open(path))

def parse_captcha():
    #argparser = argparse.ArgumentParser()
    #argparser.add_argument('path', help='Captcha file path')
    #args = argparser.parse_args()
    #path = args.path
    #print('Resolving captcha')
    captcha_text = resolve('captcha.png')
    print('Extracted Text', captcha_text)
    return captcha_text

print(parse_captcha())
