#!/usr/bin/python3
import mechanize
import pytesseract
from bs4 import BeautifulSoup as bs
from subprocess import check_output
from itertools import cycle
from get_proxies import get_proxies
import traceback

def vote(proxy):
    try:
        print('opening site')
        url = "http://158.69.76.135/"
        br.set_proxies(proxy)
        res = br.open(url + "level4.php")
        print('site opened')
        br.select_form(nr=0)
        input = br.form.find_control("id")
        input.value = '1305'
        re = br.submit().read().decode('ascii')
        state = ''
        if re == "You already voted today [12]":
            print(re)
            state = False
        else:
            state = True
        br.reload()
        return state

    except Exception as e:
        print(e)



br = mechanize.Browser()
br.set_handle_robots(False)
br.addheaders = ([('user-agent', '   Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0')])


counter = 0

proxies = get_proxies()
proxy_pool = cycle(proxies)
for i in range(1, 11):
    proxy = next(proxy_pool)
    print("Request ", i)
    try:
        print(proxy)
        print(vote(proxy))
    except:
        print("Skipping. Connection Error")

#while counter < 100:
#    state = vote()
#    print("Success" if state is True else "Failed")
#    if state is True:
#        counter += 1
#    print("Votes: ", counter)
